import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  IntroSidebar: [{type: 'autogenerated', dirName: 'Intro'}],
  NetBeansSidebar: [{type: 'autogenerated', dirName: 'NetBeans'}],
  FrontFndSidebar: [{type: 'autogenerated', dirName: 'FrontFnd'}],
  CCppSidebar: [{type: 'autogenerated', dirName: 'CCpp'}],
  CSharpSidebar: [{type: 'autogenerated', dirName: 'CSharp'}],
  JavaSidebar: [{type: 'autogenerated', dirName: 'Java'}],
  AlgorithmsSidebar: [{type: 'autogenerated', dirName: 'Algorithms'}],
  MiddlewareSidebar: [{type: 'autogenerated', dirName: 'Middleware'}],
  DatabasesSidebar: [{type: 'autogenerated', dirName: 'Databases'}],
  DevOpsSidebar: [{type: 'autogenerated', dirName: 'DevOps'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
